apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: scamper
  namespace: default
spec:
  selector:
    matchLabels:
      run: scamper
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: scamper
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      nodeSelector:
        mlab/type: 'platform'
      containers:
      - name: scamper
        image: measurementlab/traceroute-caller:v0.0.1
        volumeMounts:
        - name: scamper-data
          mountPath: /var/spool/scamper/
        - name: credentials
          mountPath: /etc/credentials
          readOnly: true
      - name: pusher
        image: measurementlab/pusher:v1.1
        env:
        - name: DIRECTORY
          value: /var/spool/scamper
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/pusher.json
        - name: BUCKET
          valueFrom:
            configMapKeyRef:
              name: pusher-dropbox
              key: bucket
        - name: EXPERIMENT
          value: scamper
        - name: MLAB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: scamper-data
          mountPath: /var/spool/scamper
        - name: credentials
          mountPath: /etc/credentials
          readOnly: true
      volumes:
      - name: scamper-data
        hostPath:
          path: /cache/core/scamper
          type: DirectoryOrCreate
      - name: credentials
        secret:
          secretName: pusher-credentials

      hostNetwork: true
